# **2.3 Lab: Introduction to Python**

## **Basic Commands**


In [9]:
# Print function
print('fit a model with', 5+6, 'variables', '\n')
print('------ Print function info ------\n')
print?

fit a model with 11 variables 

------ Print function info ------



Signature: print(*args, sep=' ', end='\n', file=None, flush=False)
Docstring:
Prints the values to a stream, or to sys.stdout by default.

sep
  string inserted between values, default a space.
end
  string appended after the last value, default a newline.
file
  a file-like object (stream); defaults to the current sys.stdout.
flush
  whether to forcibly flush the stream.
Type:      builtin_function_or_method

In [13]:
# Creating lists
x = [3, 4, 5]
y = [4, 9, 7]

# Concatenating lists
x+y

[3, 4, 5, 4, 9, 7]

## **Introduction to Numerical Python**

In [15]:
import numpy as np

# Arrays
x = np.array([3, 4, 5])
y = np.array([4, 9, 7])
x+y

array([ 7, 13, 12])

In [48]:
# Matrices
x = np.array([[1,2], [3,4]])
print(x)
print('Matrix x dimension: ' + str(x.ndim))
print('Matrix x type: ' + str(x.dtype))
print('Matrix x shape: ' + str(x.shape) + '\n')

#np.array?

[[1 2]
 [3 4]]
Matrix x dimension: 2
Matrix x type: int32
Matrix x shape: (2, 2)



In [45]:
# Methods: Sum
x = np.array([1, 2, 3, 4])
print('Sum 1: ' + str(x.sum()))
print('Sum 2: ' + str(np.sum(x)))

Sum 1: 10
Sum 2: 10


In [51]:
# Methods: Reshape
x = np.array([1, 2, 3, 4, 5, 6])
print('beginning x:\n', x)
x_reshape = x.reshape((2, 3))
print('x_reshaped:\n', x_reshape)
x_reshape[0,0] = 5
print('x_reshape after we modify its top left element:\n', x_reshape)
print('x after we modify top left element of x_reshape:\n', x)

beginning x:
 [1 2 3 4 5 6]
x_reshaped:
 [[1 2 3]
 [4 5 6]]
x_reshape after we modify its top left element:
 [[5 2 3]
 [4 5 6]]
x after we modify top left element of x_reshape:
 [5 2 3 4 5 6]


In [53]:
# Tuples
my_tuple = (3,4,5)
my_tuple[0] = 2

TypeError: 'tuple' object does not support item assignment

In [54]:
# Array attributes
x_reshape.shape , x_reshape.ndim , x_reshape.T

((2, 3),
 2,
 array([[5, 4],
        [2, 5],
        [3, 6]]))

In [63]:
# Arrays and functions
print('Square root of x: ', np.sqrt(x))
print('Square of x: ', x**2)
print('1/2 power of x: ', x**0.5)

Square root of x:  [2.23606798 1.41421356 1.73205081 2.         2.23606798 2.44948974]
Square of x:  [25  4  9 16 25 36]
1/2 power of x:  [2.23606798 1.41421356 1.73205081 2.         2.23606798 2.44948974]


In [82]:
# Random data
#np.random.normal?
x = np.random.normal(size=50)
y = x + np.random.normal(loc=50, scale=1, size=50)
print('Correlation matrix of x and y', np.corrcoef(x,y))

Correlation matrix of x and y [[1.         0.76793207]
 [0.76793207 1.        ]]


In [87]:
# Seed generation
print(rng.normal(scale=5, size=2))
rng2 = np.random.default_rng (1303)
print(rng2.normal(scale=5, size=2))

[ 4.09482632 -1.07485605]
[ 4.09482632 -1.07485605]


In [96]:
# Mean, variance and standard deviation
rng = np.random.default_rng(3)
y = rng.standard_normal(10)
print(np.mean(y), y.mean())
print(np.var(y), y.var(), np.mean((y - y.mean())**2))
print(np.sqrt(np.var(y)), np.std(y))

X = rng.standard_normal((10, 3))
print('\n'+str(X))
print('Mean among rows: ', str(X.mean(axis=0)))

-0.1126795190952861 -0.1126795190952861
2.7243406406465125 2.7243406406465125 2.7243406406465125
1.6505576756498128 1.6505576756498128

[[ 0.22578661 -0.35263079 -0.28128742]
 [-0.66804635 -1.05515055 -0.39080098]
 [ 0.48194539 -0.23855361  0.9577587 ]
 [-0.19980213  0.02425957  1.54582085]
 [ 0.54510552 -0.50522874 -0.18283897]
 [ 0.54052513  1.93508803 -0.26962033]
 [-0.24355868  1.0023136  -0.88645994]
 [-0.29172023  0.88253897  0.58035002]
 [ 0.0915167   0.67010435 -2.82816231]
 [ 1.02130682 -0.95964476 -1.66861984]]
Mean among rows:  [ 0.15030588  0.14030961 -0.34238602]
